{% set name = "langtest" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langtest-{{ version }}.tar.gz
  sha256: 556ac72ef3e8a1c1851bbfe8d22e4312f01e7607d6d3a44775279766744ff9e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - numpy
    - pandas
    - scikit-learn
    - transformers <=4.28.1
    - pytorch
    - sentencepiece
    - pydantic
    - nest-asyncio
    - jsonlines
    - langchain
    - openai
    - evaluate
    - inflect
    - rouge-score
    - typing-extensions <4.6.0
    - sympy
    - pillow

test:
  imports:
    - langtest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JohnSnowLabs/langtest/
  summary: John Snow Labs provides a library for delivering safe & effective NLP models.
  license: Apache-2.0
  license_file: LICENSE
  license_url: https://github.com/JohnSnowLabs/langtest/blob/main/LICENSE
  description: |
    `langtest` is an open-source Python library designed to help developers
    deliver safe and effective Natural Language Processing (NLP) models.

    PyPI: [https://pypi.org/project/langtest/](https://pypi.org/project/langtest/)

    ---
    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).
    
    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)
    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/JohnSnowLabs/langtest/
  doc_url: https://langtest.org/docs/pages/docs/install