# This file contains the model classes that are used in the model handler.
# from langchain

CHAT_MODEL_CLASSES = {
    "anthropic": "ChatAnthropic",
    "anyscale": "ChatAnyscale",
    "azure_openai": "AzureChatOpenAI",
    "baichuan": "ChatBaichuan",
    "baidu_qianfan_endpoint": "QianfanChatEndpoint",
    "bedrock": "BedrockChat",
    "cohere": "ChatCohere",
    "databricks": "ChatDatabricks",
    "deepinfra": "ChatDeepInfra",
    "ernie": "ErnieBotChat",
    "everlyai": "ChatEverlyAI",
    "fake": "FakeListChatModel",
    "fireworks": "ChatFireworks",
    "gigachat": "GigaChat",
    "google_palm": "ChatGooglePalm",
    "gpt_router": "GPTRouter",
    "huggingface": "ChatHuggingFace",
    "human": "HumanInputChatModel",
    "hunyuan": "ChatHunyuan",
    "javelin_ai_gateway": "ChatJavelinAIGateway",
    "jinachat": "JinaChat",
    "kinetica": "ChatKinetica",
    "konko": "ChatKonko",
    "litellm": "ChatLiteLLM",
    "litellm_router": "ChatLiteLLMRouter",
    "llama_edge": "LlamaEdgeChatService",
    "maritalk": "ChatMaritalk",
    "minimax": "MiniMaxChat",
    "mlflow": "ChatMlflow",
    "mlflow_ai_gateway": "ChatMLflowAIGateway",
    "ollama": "ChatOllama",
    "openai": "ChatOpenAI",
    "pai_eas_endpoint": "PaiEasChatEndpoint",
    "perplexity": "ChatPerplexity",
    "promptlayer_openai": "PromptLayerChatOpenAI",
    "sparkllm": "ChatSparkLLM",
    "tongyi": "ChatTongyi",
    "vertexai": "ChatVertexAI",
    "volcengine_maas": "VolcEngineMaasChat",
    "yandex": "ChatYandexGPT",
    "yuan2": "ChatYuan2",
    "zhipuai": "ChatZhipuAI",
}
